### ISSUE TITLE
Extension affected by compromised package event-stream

### ISSUE THREAD

**Issue by Regaddi** [fatihacet/gitlab-workflow#2]
This extension is affected by the latest backdoor in the event-stream package.

```bash
$ find ~ -name "event-stream"
/Users/me/.vscode/extensions/fatihacet.gitlab-workflow-1.5.0/node_modules/event-stream
```

See https://medium.com/intrinsic/compromised-npm-package-event-stream-d47d08605502

**Comment by fatihacet** [comment]
> added 397 packages from 626 contributors and audited 1237 packages in 6.696s
> found 0 vulnerabilities

Fixed with version 1.6.0.

Thanks for the issue.
