### ISSUE TITLE
Pipeline status showing old pipeline

### ISSUE THREAD

**Issue by beeing** [fatihacet/gitlab-workflow#3]
Hi, thanks for such great extension.

Currently my pipeline jobs are based on tags that starts with `v` as it is based on semver.

Also, the issue on status bar shows no issues but sidebar shows the issues correctly.

Thanks again.

**Comment by fatihacet** [comment]
Hello @beeing. This repo is just a mirror of the [original repo hosted on GitLab](https://gitlab.com/fatihacet/gitlab-vscode-extension).

There is a caching bug in the status bar and it's known. Here is the [original issue](https://gitlab.com/fatihacet/gitlab-vscode-extension/issues/38)

I am closing this one. If you have any question or feedback feel free to create an issue on GitLab.

Thanks.
